// Code generated by entc, DO NOT EDIT.

package music

const (
	// Label holds the string label denoting the music type in the database.
	Label = "music"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the music in the database.
	Table = "musics"
	// ClubTable is the table the holds the club relation/edge.
	ClubTable = "musics"
	// ClubInverseTable is the table name for the Club entity.
	// It exists in this package in order to avoid circular dependency with the "club" package.
	ClubInverseTable = "clubs"
	// ClubColumn is the table column denoting the club relation/edge.
	ClubColumn = "club_id"
)

// Columns holds all SQL columns are music fields.
var Columns = []string{
	FieldID,
}
