// Code generated by entc, DO NOT EDIT.

package club

const (
	// Label holds the string label denoting the club type in the database.
	Label = "club"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"

	// Table holds the table name of the club in the database.
	Table = "clubs"
	// MusicTable is the table the holds the music relation/edge.
	MusicTable = "musics"
	// MusicInverseTable is the table name for the Music entity.
	// It exists in this package in order to avoid circular dependency with the "music" package.
	MusicInverseTable = "musics"
	// MusicColumn is the table column denoting the music relation/edge.
	MusicColumn = "club_id"
	// UserTable is the table the holds the user relation/edge. The primary key declared below.
	UserTable = "club_user"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
)

// Columns holds all SQL columns are club fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// UserPrimaryKey and UserColumn2 are the table columns denoting the
	// primary key for the user relation (M2M).
	UserPrimaryKey = []string{"club_id", "user_id"}
)
