// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/Shikugawa/potluq/ent/club"
	"github.com/Shikugawa/potluq/ent/music"
	"github.com/Shikugawa/potluq/ent/predicate"
	"github.com/Shikugawa/potluq/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ClubUpdate is the builder for updating Club entities.
type ClubUpdate struct {
	config
	name         *string
	music        map[int]struct{}
	user         map[int]struct{}
	removedMusic map[int]struct{}
	removedUser  map[int]struct{}
	predicates   []predicate.Club
}

// Where adds a new predicate for the builder.
func (cu *ClubUpdate) Where(ps ...predicate.Club) *ClubUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetName sets the name field.
func (cu *ClubUpdate) SetName(s string) *ClubUpdate {
	cu.name = &s
	return cu
}

// AddMusicIDs adds the music edge to Music by ids.
func (cu *ClubUpdate) AddMusicIDs(ids ...int) *ClubUpdate {
	if cu.music == nil {
		cu.music = make(map[int]struct{})
	}
	for i := range ids {
		cu.music[ids[i]] = struct{}{}
	}
	return cu
}

// AddMusic adds the music edges to Music.
func (cu *ClubUpdate) AddMusic(m ...*Music) *ClubUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cu.AddMusicIDs(ids...)
}

// AddUserIDs adds the user edge to User by ids.
func (cu *ClubUpdate) AddUserIDs(ids ...int) *ClubUpdate {
	if cu.user == nil {
		cu.user = make(map[int]struct{})
	}
	for i := range ids {
		cu.user[ids[i]] = struct{}{}
	}
	return cu
}

// AddUser adds the user edges to User.
func (cu *ClubUpdate) AddUser(u ...*User) *ClubUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cu.AddUserIDs(ids...)
}

// RemoveMusicIDs removes the music edge to Music by ids.
func (cu *ClubUpdate) RemoveMusicIDs(ids ...int) *ClubUpdate {
	if cu.removedMusic == nil {
		cu.removedMusic = make(map[int]struct{})
	}
	for i := range ids {
		cu.removedMusic[ids[i]] = struct{}{}
	}
	return cu
}

// RemoveMusic removes music edges to Music.
func (cu *ClubUpdate) RemoveMusic(m ...*Music) *ClubUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cu.RemoveMusicIDs(ids...)
}

// RemoveUserIDs removes the user edge to User by ids.
func (cu *ClubUpdate) RemoveUserIDs(ids ...int) *ClubUpdate {
	if cu.removedUser == nil {
		cu.removedUser = make(map[int]struct{})
	}
	for i := range ids {
		cu.removedUser[ids[i]] = struct{}{}
	}
	return cu
}

// RemoveUser removes user edges to User.
func (cu *ClubUpdate) RemoveUser(u ...*User) *ClubUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cu.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *ClubUpdate) Save(ctx context.Context) (int, error) {
	return cu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClubUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClubUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClubUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ClubUpdate) sqlSave(ctx context.Context) (n int, err error) {
	spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   club.Table,
			Columns: club.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: club.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := cu.name; value != nil {
		spec.Fields.Set = append(spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: club.FieldName,
		})
	}
	if nodes := cu.removedMusic; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   club.MusicTable,
			Columns: []string{club.MusicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: music.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := cu.music; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   club.MusicTable,
			Columns: []string{club.MusicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: music.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if nodes := cu.removedUser; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.UserTable,
			Columns: club.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := cu.user; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.UserTable,
			Columns: club.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ClubUpdateOne is the builder for updating a single Club entity.
type ClubUpdateOne struct {
	config
	id           int
	name         *string
	music        map[int]struct{}
	user         map[int]struct{}
	removedMusic map[int]struct{}
	removedUser  map[int]struct{}
}

// SetName sets the name field.
func (cuo *ClubUpdateOne) SetName(s string) *ClubUpdateOne {
	cuo.name = &s
	return cuo
}

// AddMusicIDs adds the music edge to Music by ids.
func (cuo *ClubUpdateOne) AddMusicIDs(ids ...int) *ClubUpdateOne {
	if cuo.music == nil {
		cuo.music = make(map[int]struct{})
	}
	for i := range ids {
		cuo.music[ids[i]] = struct{}{}
	}
	return cuo
}

// AddMusic adds the music edges to Music.
func (cuo *ClubUpdateOne) AddMusic(m ...*Music) *ClubUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cuo.AddMusicIDs(ids...)
}

// AddUserIDs adds the user edge to User by ids.
func (cuo *ClubUpdateOne) AddUserIDs(ids ...int) *ClubUpdateOne {
	if cuo.user == nil {
		cuo.user = make(map[int]struct{})
	}
	for i := range ids {
		cuo.user[ids[i]] = struct{}{}
	}
	return cuo
}

// AddUser adds the user edges to User.
func (cuo *ClubUpdateOne) AddUser(u ...*User) *ClubUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cuo.AddUserIDs(ids...)
}

// RemoveMusicIDs removes the music edge to Music by ids.
func (cuo *ClubUpdateOne) RemoveMusicIDs(ids ...int) *ClubUpdateOne {
	if cuo.removedMusic == nil {
		cuo.removedMusic = make(map[int]struct{})
	}
	for i := range ids {
		cuo.removedMusic[ids[i]] = struct{}{}
	}
	return cuo
}

// RemoveMusic removes music edges to Music.
func (cuo *ClubUpdateOne) RemoveMusic(m ...*Music) *ClubUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cuo.RemoveMusicIDs(ids...)
}

// RemoveUserIDs removes the user edge to User by ids.
func (cuo *ClubUpdateOne) RemoveUserIDs(ids ...int) *ClubUpdateOne {
	if cuo.removedUser == nil {
		cuo.removedUser = make(map[int]struct{})
	}
	for i := range ids {
		cuo.removedUser[ids[i]] = struct{}{}
	}
	return cuo
}

// RemoveUser removes user edges to User.
func (cuo *ClubUpdateOne) RemoveUser(u ...*User) *ClubUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cuo.RemoveUserIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *ClubUpdateOne) Save(ctx context.Context) (*Club, error) {
	return cuo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClubUpdateOne) SaveX(ctx context.Context) *Club {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *ClubUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClubUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ClubUpdateOne) sqlSave(ctx context.Context) (c *Club, err error) {
	spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   club.Table,
			Columns: club.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  cuo.id,
				Type:   field.TypeInt,
				Column: club.FieldID,
			},
		},
	}
	if value := cuo.name; value != nil {
		spec.Fields.Set = append(spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: club.FieldName,
		})
	}
	if nodes := cuo.removedMusic; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   club.MusicTable,
			Columns: []string{club.MusicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: music.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := cuo.music; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   club.MusicTable,
			Columns: []string{club.MusicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: music.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if nodes := cuo.removedUser; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.UserTable,
			Columns: club.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := cuo.user; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   club.UserTable,
			Columns: club.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	c = &Club{config: cuo.config}
	spec.Assign = c.assignValues
	spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
