// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/Shikugawa/potluq/ent/music"
	"github.com/Shikugawa/potluq/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// MusicDelete is the builder for deleting a Music entity.
type MusicDelete struct {
	config
	predicates []predicate.Music
}

// Where adds a new predicate to the delete builder.
func (md *MusicDelete) Where(ps ...predicate.Music) *MusicDelete {
	md.predicates = append(md.predicates, ps...)
	return md
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (md *MusicDelete) Exec(ctx context.Context) (int, error) {
	return md.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (md *MusicDelete) ExecX(ctx context.Context) int {
	n, err := md.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (md *MusicDelete) sqlExec(ctx context.Context) (int, error) {
	spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: music.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: music.FieldID,
			},
		},
	}
	if ps := md.predicates; len(ps) > 0 {
		spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, md.driver, spec)
}

// MusicDeleteOne is the builder for deleting a single Music entity.
type MusicDeleteOne struct {
	md *MusicDelete
}

// Exec executes the deletion query.
func (mdo *MusicDeleteOne) Exec(ctx context.Context) error {
	n, err := mdo.md.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{music.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mdo *MusicDeleteOne) ExecX(ctx context.Context) {
	mdo.md.ExecX(ctx)
}
