// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email vertex property in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password vertex property in the database.
	FieldPassword = "password"

	// Table holds the table name of the user in the database.
	Table = "users"
	// DeviceTable is the table the holds the device relation/edge. The primary key declared below.
	DeviceTable = "device_user"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "devices"
)

// Columns holds all SQL columns are user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
}

var (
	// DevicePrimaryKey and DeviceColumn2 are the table columns denoting the
	// primary key for the device relation (M2M).
	DevicePrimaryKey = []string{"device_id", "user_id"}
)
