// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email vertex property in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password vertex property in the database.
	FieldPassword = "password"

	// Table holds the table name of the user in the database.
	Table = "users"
	// ClubTable is the table the holds the club relation/edge. The primary key declared below.
	ClubTable = "club_user"
	// ClubInverseTable is the table name for the Club entity.
	// It exists in this package in order to avoid circular dependency with the "club" package.
	ClubInverseTable = "clubs"
)

// Columns holds all SQL columns are user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
}

var (
	// ClubPrimaryKey and ClubColumn2 are the table columns denoting the
	// primary key for the club relation (M2M).
	ClubPrimaryKey = []string{"club_id", "user_id"}
)
