// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Club is the predicate function for club builders.
type Club func(*sql.Selector)

// Music is the predicate function for music builders.
type Music func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
